apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: my-org
      defaultBucket: health_db
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-token
