{
 "title": "New dashboard",
 "time": { "from": "2016-04-03T17:56:16.474Z", "to": "2016-04-03T22:45:12.577Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Heart Rate Anomaly Logs",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"health_db\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"anomalies\")\n  |> filter(fn: (r) => r[\"user_id\"] == \"user_5577150313\")\n  |> filter(fn: (r) => r[\"_field\"] == \"message\")\n  |> keep(columns: [\"_time\", \"_value\", \"anomaly_type\"])\n  |> rename(columns: {_time: \"time\", _value: \"message\"})\n  |> sort(columns: [\"time\"], desc: true)\n"
    }
   ]
  },
  {
   "title": "BPM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"health_db\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._field == \"heart_rate\")\n  |> last()\n"
    }
   ]
  },
  {
   "title": "All sensors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"health_db\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"heart_rate\" or r._field == \"calories\" or r._field == \"sleep\" or r._field == \"intensities\" or r._field == \"steps\")\n\n"
    }
   ]
  },
  {
   "title": "Steps last 24 hours",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"health_db\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"user_health\")\n  |> filter(fn: (r) => r._field == \"steps\")\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Calories last 24 hours",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"health_db\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"user_health\")\n  |> filter(fn: (r) => r[\"_field\"] == \"calories\")\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Heart rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"health_db\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop )\n  |> filter(fn: (r) => r._field == \"heart_rate\")\n\n"
    }
   ]
  },
  {
   "title": "Sleep time last 24 hours",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"health_db\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"user_health\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sleep\")\n  |> filter(fn: (r) => r._value != 0)\n  |> aggregateWindow(every: 1m, fn: last, createEmpty: false)\n  |> aggregateWindow(every: 1d, fn: count, createEmpty: false)\n  |> map(fn: (r) => ({\n      Minutes: r._value,\n      \"Sleep Duration\": string(v: int(v: float(v: r._value) / 60.0)) + \"h \" + string(v: int(v: float(v: r._value) % 60.0)) + \"m\"\n  }))\n \n"
    }
   ]
  },
  {
   "title": "Sleep",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "query": "from(bucket: \"health_db\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"user_health\")\n  |> filter(fn: (r) => r[\"_field\"] == \"sleep\")\n  |> filter(fn: (r) => r._value == 1 or r._value == 2 or r._value == 3 or r._value == 4)\n  |> aggregateWindow(every: 1m, fn: last, createEmpty: false)\n  |> aggregateWindow(every: 1d, fn: count, createEmpty: false)\n  |> map(fn: (r) => ({\n      Minutes: r._value,\n      \"Sleep Duration\": string(v: int(v: float(v: r._value) / 60.0)) + \"h \" + string(v: int(v: float(v: r._value) % 60.0)) + \"m\"\n  }))\n "
    }
   ]
  },
  {
   "title": "Heart rate distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "query": "from(bucket: \"health_db\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._field == \"heart_rate\")\n"
    }
   ]
  },
  {
   "title": "Steps",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
   "targets": [
    {
     "query": "from(bucket: \"health_db\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"user_health\")\n  |> filter(fn: (r) => r[\"_field\"] == \"steps\")\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\n  "
    }
   ]
  },
  {
   "title": "Intensities ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 42 },
   "targets": [
    {
     "query": "from(bucket: \"health_db\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"user_health\")\n  |> filter(fn: (r) => r[\"_field\"] == \"intensities\")\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\n\n"
    }
   ]
  },
  {
   "title": "Calories ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 42 },
   "targets": [
    {
     "query": "from(bucket: \"health_db\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"user_health\")\n  |> filter(fn: (r) => r[\"_field\"] == \"calories\")\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  }
 ]
}