{
 "title": "New dashboard",
 "time": { "from": "2016-04-03T17:56:16.474Z", "to": "2016-04-03T22:45:12.577Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "BPM",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"health_db\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._field == \"heart_rate\")\n  |> last()\n"
    }
   ]
  },
  {
   "title": "All sensors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"health_db\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"heart_rate\" or r._field == \"calories\" or r._field == \"sleep\" or r._field == \"intensities\" or r._field == \"steps\")\n\n"
    }
   ]
  },
  {
   "title": "Steps last 24 hours",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"health_db\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"user_health\")\n  |> filter(fn: (r) => r._field == \"steps\")\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Today's calories ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"health_db\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"user_health\")\n  |> filter(fn: (r) => r[\"_field\"] == \"calories\")\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Heart rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"health_db\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop )\n  |> filter(fn: (r) => r._field == \"heart_rate\")\n\n"
    }
   ]
  },
  {
   "title": "Sleep time last 24 hours",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"health_db\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_field\"] == \"sleep\")\n  |> aggregateWindow(\n    every: 1d,\n    fn: count,\n    createEmpty: false\n  )\n  |> group()\n  |> map(fn: (r) => ({\n      \"Date\": r._time,\n      \"Total Minutes\": r._value,\n      \"Sleep Duration\": \"${string(v: int(v: float(v: r._value) / 60.0))}h ${string(v: int(v: float(v: r._value) % 60.0))}m\"\n  }))\n"
    }
   ]
  },
  {
   "title": "Sleep",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "query": " from(bucket: \"health_db\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_field\"] == \"sleep\")\n  |> aggregateWindow(\n    every: 1d,\n    fn: count,\n    createEmpty: false\n  )\n  |> group()\n  |> map(fn: (r) => ({\n      \"Date\": r._time,\n      \"Total Minutes\": r._value,\n      \"Sleep Duration\": \"${string(v: int(v: float(v: r._value) / 60.0))}h ${string(v: int(v: float(v: r._value) % 60.0))}m\"\n  }))\n"
    }
   ]
  },
  {
   "title": "Heart rate distribution",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "query": "from(bucket: \"health_db\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r._field == \"heart_rate\")\n"
    }
   ]
  },
  {
   "title": "Steps",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "targets": [
    {
     "query": "from(bucket: \"health_db\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"user_health\")\n  |> filter(fn: (r) => r[\"_field\"] == \"steps\")\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\n  "
    }
   ]
  },
  {
   "title": "Intensities ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 33 },
   "targets": [
    {
     "query": "from(bucket: \"health_db\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"user_health\")\n  |> filter(fn: (r) => r[\"_field\"] == \"intensities\")\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Calories ",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 33 },
   "targets": [
    {
     "query": "from(bucket: \"health_db\")\n  |> range(start: 0)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"user_health\")\n  |> filter(fn: (r) => r[\"_field\"] == \"calories\")\n  |> aggregateWindow(every: 1d, fn: sum, createEmpty: false)\n  |> yield(name: \"sum\")"
    }
   ]
  }
 ]
}